server:
  base_port: 3333
  server_count: 2

rules:
  - id: "rule1"
    path_rule:
        path: "/api"
        type: "PREFIX"
    header_rules:
      - key: "Yasas"
        value: "tharinda"
    pool:
      load_balancer: "RANDOMLOADBALANCER"
      backends:
        - url: "http://localhost:3000"
          weight: 1
        - url: "http://localhost:3001"
          weight: 1
        - url: "http://localhost:3002"
          weight: 1
  - id: "rule2"
    path_rule:
        path: "/pet"
        type: "PREFIX"
    pool:
      load_balancer: "WEIGHTEDLOADBALANCER"
      backends:
        - url: "http://localhost:3000"
          weight: 1
        - url: "http://localhost:3001"
          weight: 1
        - url: "http://localhost:3002"
          weight: 1
